### PR TITLE
Replace go.uber.org/multierr with errors.Join

### PR DESCRIPTION
**Pull request by dominikschulz**
Since Go has gained native multi-error support we can drop the dependency on `go.uber.org/multierr` in favor of the stdlib `errors.Join`.

### CODE REVIEW

**Comment by twpayne** [comment]
Thanks for this. This package needs to support the stable and old stable versions of Go, currently 1.20 and 1.19. As `errors.Join` was only added in Go 1.20, this can only be merged when Go 1.21 is released.

I need to update the build infrastructure to support this.

**Comment by dominikschulz** [comment]
Sounds good. Feel free to keep it around till then.

**Comment by twpayne** [comment]
It turns out that `errors.Join` doesn't quite have the desired behavior. Specifically, if `errors.Join` is called with exactly one non-nil error then it wraps that error in `[]error{}` rather than leaving it unchanged. #8 uses a different function, but still removes the dependency on go.uber.org/multierr, with you credited as co-author.

**Comment by twpayne** [comment]
I've tagged `v0.3.0` with the dependency removed.

**Pull request closed without merging**
